Repository Pacific-Agency/nuxt-utils, pull requests merged in 2023-03, with the labels that each got.

#28 Стилизация документации
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/theme.css
  docs/assets/logo.svg
  docs/index.md
Labels: Разработка

#34 Обновление `README`
  README.md
Labels: Разработка

#33 Добавление `CODEOWNERS`
  .github/CODEOWNERS
Labels: Разработка

#30 Нет лого в документации
  docs/.vitepress/config.ts
  docs/index.md
  docs/public/favicon.ico
  docs/public/logo.svg
Labels: Баг

#43 Создание эндпоинта для `sitemap`
  docs/.vitepress/config.ts
  docs/api/sitemap.md
  src/module.ts
  src/runtime/api/sitemap-routes.ts
  tests/components/MapWidget.spec.ts
  tests/composables/usePhoneFormatter.spec.ts
  tests/composables/usePriceFormatter.spec.ts
  tests/fixtures/basic/app.vue
  tests/fixtures/basic/nuxt.config.ts
  tests/fixtures/basic/package.json
Labels: Фича

#42 Создание `composable` `useSubmitForm`
  docs/.vitepress/config.ts
  docs/composables/use-submit-form.md
  src/runtime/composables/useSubmitForm.ts
Labels: Фича

#44 Обновление `pnpm` до `v8.1.0`
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .github/workflows/release-package.yml
  package.json
  pnpm-lock.yaml
Labels: Рефактор
