Repository Pacific-Agency/nuxt-utils, pull requests merged in 2023-05, with the labels that each got.

#84 Неправильно определен тип `url` в `useFetchAuth`
  src/runtime/composables/useFetchAuth.ts
Labels: Баг

#91 Неправильный порядок параметров `defu` в `useFetchAuth`
  src/runtime/composables/useFetchAuth.ts
Labels: Баг

#93 Добавление префикса к компонентам
  docs/.vitepress/config.ts
  docs/components/map-widget.md
  playground/app.vue
  src/runtime/components/UtilsMapWidget.vue
  tests/components/MapWidget.spec.ts
Labels: Рефактор

#95 Использование общего репозитория `workflows`
  .github/workflows/ci.yml
  .github/workflows/update-package-json.yml
Labels: Разработка

#97 Общие инпуты для форм
  docs/.vitepress/config.ts
  docs/components/input.md
  docs/components/phone.md
  docs/components/textarea.md
  docs/index.md
  docs/installation.md
  package.json
  pnpm-lock.yaml
  src/runtime/components/UtilsInput.vue
  src/runtime/components/UtilsPhone.vue
  src/runtime/components/UtilsTextArea.vue
  tests/components/UtilsInput.spec.ts
  tests/components/UtilsMapWidget.spec.ts
  tests/components/UtilsPhone.spec.ts
  tests/components/UtilsTextArea.spec.ts
  vitest.config.ts
Labels: Фича

#99 Добавление `local: true` для компонентов формы
  docs/components/input.md
  docs/components/phone.md
  docs/components/textarea.md
  src/runtime/components/UtilsInput.vue
  src/runtime/components/UtilsPhone.vue
  src/runtime/components/UtilsTextArea.vue
  tests/components/UtilsInput.spec.ts
  tests/components/UtilsPhone.spec.ts
  tests/components/UtilsTextArea.spec.ts
Labels: Рефактор

#100 Функция `useSubmitForm` возвращает `undefined` вместо ошибки
  src/runtime/composables/useSubmitForm.ts
Labels: Баг

#102 Отсутствует `BOT_ACCESS_TOKEN` в `workflows`
  .github/workflows/update-package-json.yml
Labels: Разработка
