Repository Pacific-Agency/nuxt-utils, pull requests merged in 2023-07, with the labels that each got.

#132 feat: Компонент `UtilsPassword`
  docs/.vitepress/config.ts
  docs/components/password.md
  package.json
  pnpm-lock.yaml
  src/runtime/components/UtilsPassword.vue
  tests/components/UtilsPassword.spec.ts
Labels: Фича

#133 docs: Обновление документации включения `defineModel`
  docs/components/input-masked.md
  docs/components/input.md
  docs/components/password.md
  docs/components/phone.md
  docs/components/textarea.md
Labels: Документация

#135 fix: Стандартное значение атрибута `ID` у `UtilsPassword`
  docs/components/password.md
  src/runtime/components/UtilsPassword.vue
  tests/components/UtilsPassword.spec.ts
Labels: Баг

#139 feat: Функция `useScrollArrows`
  docs/.vitepress/config.ts
  docs/composables/use-scroll-slider.md
  src/runtime/composables/useScrollSlider.ts
  src/runtime/composables/useSubmitForm.ts
Labels: Фича

#141 fix: Замена названий переменных крайнего правого и левого края
  docs/composables/use-scroll-slider.md
  src/runtime/composables/useScrollSlider.ts
Labels: Баг
