Repository Pacific-Agency/nuxt-utils, pull requests merged in 2023-04, with the labels that each got.

#47 Замена автоимпорта на явный
  .nuxtrc
  package.json
  playground/app.vue
  pnpm-lock.yaml
  src/runtime/api/sitemap-routes.ts
  src/runtime/composables/useScrollLock.ts
  src/runtime/composables/useSubmitForm.ts
  tsconfig.json
Labels: Рефактор

#50 Не работает эндпоинт для `Sitemap`
  src/module.ts
  src/runtime/api/sitemap-routes.ts
Labels: Баг

#51 Обработка ошибки 404 для `Sitemap`
  src/runtime/api/sitemap-routes.ts
Labels: Рефактор

#55 Реактивный параметр `url` для `useSubmitForm`
  docs/composables/use-submit-form.md
  src/runtime/composables/useSubmitForm.ts
Labels: Рефактор

#64 Функция `useFetchAuth`
  docs/.vitepress/config.ts
  docs/composables/use-fetch-auth.md
  docs/index.md
  src/runtime/composables/useFetchAuth.ts
Labels: Фича

#66 Порядок установки и использования в документации
  README.md
  docs/.vitepress/config.ts
  docs/index.md
  docs/installation.md
Labels: Разработка

#69 Отсутствует `credentials="include"` в `useFetchAuth`
  src/runtime/composables/useFetchAuth.ts
Labels: Баг

#73 Рефактор функции `useFetchAuth`
  docs/composables/use-fetch-auth.md
  src/runtime/composables/useFetchAuth.ts
Labels: Рефактор

#75 Неправильный тип ответа от `useFetchAuth`
  src/runtime/composables/useFetchAuth.ts
Labels: Баг

#79 Рефактор параметров `useFetchAuth`
  src/runtime/composables/useFetchAuth.ts
Labels: Рефактор
